#cloud-config
runcmd:
  # General installation
  - apt update -y
  - DEBIAN_FRONTEND=noninteractive apt upgrade -y
  # Docker setup
  - DEBIAN_FRONTEND=noninteractive apt -y install ca-certificates curl gnupg lsb-release jq
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt update -y
  - DEBIAN_FRONTEND=noninteractive apt install -y docker-ce docker-ce-cli containerd.io
  # Fix for iptables
  - |
    echo br_netfilter > /etc/modules-load.d/k8s.conf
    printf "net.bridge.bridge-nf-call-ip6tables = 1\nnet.bridge.bridge-nf-call-iptables = 1" | sudo tee /etc/sysctl.d/k8s.conf
    sysctl --system
  # Fix for docker
  - >
    echo
    '{"exec-opts": ["native.cgroupdriver=cgroupfs"]}'
    > /etc/docker/daemon.json
  - systemctl daemon-reload; systemctl restart docker
  # Kubeadm install
  - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt update -y
  - DEBIAN_FRONTEND=noninteractive apt install -y kubelet kubeadm kubectl
  # Setup user and keys
  - yes | adduser user --home /home/user --disabled-password --quiet
  - usermod -aG docker user
  - usermod -aG sudo user
  - mkdir -p /home/user/.kube /home/user/.ssh
  - echo "${pubkey}" | base64 --decode >> /home/user/.ssh/authorized_keys
  - echo "${pubkey}" | base64 --decode > /home/user/.ssh/id_rsa.pub
  - echo "${privatekey}" | base64 --decode > /home/user/.ssh/id_rsa
  # Add root keys
  - echo "${pubkey}" | base64 --decode > /root/.ssh/id_rsa.pub
  - echo "${privatekey}" | base64 --decode > /root/.ssh/id_rsa
  # Fix permissions
  - chown 700 /home/user/.kube /home/user/.ssh
  - chown -R user:user /home/user/.kube/ /home/user/.ssh
  - chmod -R 600 /home/user/.ssh/*
  - chmod -R 600 /root/.ssh/*
  - service ssh restart
  # Fix node IPs
  - |
    printf "[Service]\nEnvironment=\"KUBELET_KUBEADM_ARGS=--cgroup-driver=cgroupfs --network-plugin=cni KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs KUBELET_EXTRA_ARGS=--node-ip=${node_ip}\"" > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    systemctl daemon-reload
    systemctl restart kubelet.service
  # Kubemaster setup
  - >
    if grep -q "master-1" "/etc/hostname"; then
      kubeadm init --control-plane-endpoint=master-1.internal.k8s.${domain_name} --apiserver-advertise-address=${node_ip} --pod-network-cidr=10.10.1.0/24;
      cp /etc/kubernetes/admin.conf /home/user/.kube/config; chown user:user /home/user/.kube/config;
      KUBECONFIG=/home/user/.kube/config kubectl apply -f "https://cloud.weave.works/k8s/net?env.IPALLOC_RANGE=10.10.1.0/24&k8s-version=$(kubectl version | base64 | tr -d '\n')";
      echo "KUBECONFIG=/home/user/.kube/config" >> /etc/environment;
      kubeadm token list -o json | jq ".token" | tr -d '"' > /kube-token.txt;
      openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //' > /kube-hash.txt;
    fi
  # Node setup
  - >
    if grep -q "node" "/etc/hostname"; then
      while ! scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null user@master-1.internal.k8s.${domain_name}:/kube-* /; do sleep 5; done;
      kubeadm join master-1.internal.k8s.${domain_name}:6443 --token "$(cat /kube-token.txt)" --discovery-token-ca-cert-hash sha256:"$(cat /kube-hash.txt)";
    fi
  # Untained master nodes
  - >
    if grep -q "master-1" "/etc/hostname"; then KUBECONFIG=/home/user/.kube/config kubectl taint nodes --all node-role.kubernetes.io/master-; fi

# /etc/sysconfig/network-scripts/route-enp0s3:: ip route add 10.96.0.1/32 dev enp0s3 ???
# failed to run Kubelet: misconfiguration: kubelet cgroup driver: \"cgroupfs\" is different from docker cgroup driver: \"systemd
output:
  all: "| tee -a /var/log/cloud-init-setup.log"